# Generated by Django 5.2.16 on 2026-07-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('section_key', models.SlugField(help_text='history, mission, vision, values, market…', max_length=64, unique=True, verbose_name='Ключ секції')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('body_ru', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('body_uz', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('body_en', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Секція «Про компанію»',
                'verbose_name_plural': 'Секції «Про компанію»',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('icon_key', models.CharField(blank=True, help_text='Ідентифікатор іконки у фронтенді', max_length=64, verbose_name='Ключ іконки')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Опис')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('text_uz', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Перевага',
                'verbose_name_plural': 'Переваги',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('text_uz', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('metric', models.CharField(blank=True, max_length=128, verbose_name='Метрика')),
                ('metric_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='Метрика')),
                ('metric_uz', models.CharField(blank=True, max_length=128, null=True, verbose_name='Метрика')),
                ('metric_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='Метрика')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейси',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('value', models.CharField(max_length=64, verbose_name='Значення')),
                ('label', models.CharField(max_length=255, verbose_name='Підпис')),
                ('label_ru', models.CharField(max_length=255, null=True, verbose_name='Підпис')),
                ('label_uz', models.CharField(max_length=255, null=True, verbose_name='Підпис')),
                ('label_en', models.CharField(max_length=255, null=True, verbose_name='Підпис')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Цифра',
                'verbose_name_plural': 'Цифри',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('body_ru', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('body_uz', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('body_en', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Правовий документ',
                'verbose_name_plural': 'Правові документи',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='PartnerOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Опис')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('text_uz', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Пропозиція для партнерів',
                'verbose_name_plural': 'Пропозиції для партнерів',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='AJERES', max_length=255, verbose_name='Назва компанії')),
                ('company_name_ru', models.CharField(default='AJERES', max_length=255, null=True, verbose_name='Назва компанії')),
                ('company_name_uz', models.CharField(default='AJERES', max_length=255, null=True, verbose_name='Назва компанії')),
                ('company_name_en', models.CharField(default='AJERES', max_length=255, null=True, verbose_name='Назва компанії')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адреса')),
                ('address_ru', models.TextField(blank=True, null=True, verbose_name='Адреса')),
                ('address_uz', models.TextField(blank=True, null=True, verbose_name='Адреса')),
                ('address_en', models.TextField(blank=True, null=True, verbose_name='Адреса')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
        migrations.CreateModel(
            name='SiteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(db_index=True, max_length=64, verbose_name='Сторінка')),
                ('key', models.CharField(max_length=128, verbose_name='Ключ')),
                ('text_html', models.TextField(blank=True, default='', verbose_name='Текст / HTML / visibility')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cms/blocks/', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'CMS-блок',
                'verbose_name_plural': 'CMS-блоки',
                'ordering': ['page', 'key'],
                'constraints': [models.UniqueConstraint(fields=('page', 'key'), name='uniq_siteblock_page_key')],
            },
        ),
    ]
