# Generated by Django 5.2.16 on 2026-07-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='core/retail_partners/', verbose_name='Логотип')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Покупець (ритейл)',
                'verbose_name_plural': 'Покупці (ритейл)',
                'ordering': ['order', 'name'],
            },
        ),
    ]
