# Generated by Django 5.2.16 on 2026-08-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_retail_partner_and_brand_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteButtonStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_type', models.CharField(choices=[('solid', 'Однотонний'), ('gradient', 'Градієнт')], default='gradient', max_length=16, verbose_name='Тип заливки')),
                ('solid_color', models.CharField(blank=True, default='', help_text='Hex, напр. #FF5A36', max_length=7, verbose_name='Однотонний колір')),
                ('gradient_start', models.CharField(blank=True, default='#ff7a52', help_text='Hex', max_length=7, verbose_name='Градієнт — початок')),
                ('gradient_end', models.CharField(blank=True, default='#e04822', help_text='Hex', max_length=7, verbose_name='Градієнт — кінець')),
                ('gradient_angle', models.PositiveSmallIntegerField(default=145, help_text='0–360', verbose_name='Кут градієнта (°)')),
                ('role', models.CharField(choices=[('primary', 'Primary (основна CTA)'), ('secondary', 'Secondary'), ('header', 'Header'), ('modal', 'Modal')], max_length=32, unique=True, verbose_name='Роль кнопки')),
            ],
            options={
                'verbose_name': 'Стиль кнопки',
                'verbose_name_plural': 'Стилі кнопок',
                'ordering': ['role'],
            },
        ),
        migrations.CreateModel(
            name='AboutAboutSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Про компанію',
                'verbose_name_plural': 'Про компанію',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='ContactsContactsSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Контакти',
                'verbose_name_plural': 'Контакти',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeAdvantagesSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Переваги',
                'verbose_name_plural': 'Головна — Переваги',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeBrandsSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Бренди',
                'verbose_name_plural': 'Головна — Бренди',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeCoopSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Співпраця',
                'verbose_name_plural': 'Головна — Співпраця',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeCtaSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — CTA',
                'verbose_name_plural': 'Головна — CTA',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeHeroSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Hero',
                'verbose_name_plural': 'Головна — Hero',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#ff5a36', help_text='Hex, напр. #FF5A36', max_length=7, verbose_name='Акцентний колір'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='accent_ink',
            field=models.CharField(default='#db3f1c', help_text='Hex', max_length=7, verbose_name='Акцент (темніший / hover)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='accent_soft',
            field=models.CharField(default='#fff0ea', help_text='Hex', max_length=7, verbose_name='Акцент (мʼякий фон)'),
        ),
        migrations.CreateModel(
            name='BlockStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_type', models.CharField(choices=[('solid', 'Однотонний'), ('gradient', 'Градієнт')], default='gradient', max_length=16, verbose_name='Тип заливки')),
                ('solid_color', models.CharField(blank=True, default='', help_text='Hex, напр. #FF5A36', max_length=7, verbose_name='Однотонний колір')),
                ('gradient_start', models.CharField(blank=True, default='#ff7a52', help_text='Hex', max_length=7, verbose_name='Градієнт — початок')),
                ('gradient_end', models.CharField(blank=True, default='#e04822', help_text='Hex', max_length=7, verbose_name='Градієнт — кінець')),
                ('gradient_angle', models.PositiveSmallIntegerField(default=145, help_text='0–360', verbose_name='Кут градієнта (°)')),
                ('page', models.CharField(db_index=True, max_length=64, verbose_name='Сторінка')),
                ('section_key', models.CharField(max_length=64, verbose_name='Секція')),
                ('label', models.CharField(blank=True, max_length=128, verbose_name='Назва в адмінці')),
                ('bg_color', models.CharField(blank=True, default='', help_text='Hex. Порожньо = CSS за замовчуванням', max_length=7, verbose_name='Колір фону секції')),
                ('override_button_fill', models.BooleanField(default=False, help_text='Якщо увімкнено — fill_* нижче замінюють глобальні стилі кнопок у цій секції', verbose_name='Override заливки кнопок у секції')),
            ],
            options={
                'verbose_name': 'Стиль секції',
                'verbose_name_plural': 'Стилі секцій',
                'ordering': ['page', 'section_key'],
                'constraints': [models.UniqueConstraint(fields=('page', 'section_key'), name='uniq_blockstyle_page_section')],
            },
        ),
    ]
