# Generated by Django 5.2.16 on 2026-08-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_theme_styles_and_accents'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteblock',
            name='text_html_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Текст / HTML / visibility'),
        ),
        migrations.AddField(
            model_name='siteblock',
            name='text_html_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Текст / HTML / visibility'),
        ),
        migrations.AddField(
            model_name='siteblock',
            name='text_html_uz',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Текст / HTML / visibility'),
        ),
    ]
