# Generated by Django 5.2.16 on 2026-07-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField(verbose_name='Мета звернення')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=64, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('uz', "O'zbekcha"), ('en', 'English')], default='ru', max_length=8, verbose_name='Мова')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('processed', 'Опрацьована')], db_index=True, default='new', max_length=16, verbose_name='Статус')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
