# Generated by Django 5.2.16 on 2026-07-20 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('logo', models.ImageField(upload_to='catalog/brands/', verbose_name='Логотип')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткий опис')),
                ('short_description_ru', models.TextField(blank=True, null=True, verbose_name='Короткий опис')),
                ('short_description_uz', models.TextField(blank=True, null=True, verbose_name='Короткий опис')),
                ('short_description_en', models.TextField(blank=True, null=True, verbose_name='Короткий опис')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_featured', models.BooleanField(default=True, help_text='Показувати в блоці брендів на головній', verbose_name='На головній')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренди',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/categories/', verbose_name='Зображення')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Slug')),
                ('name', models.CharField(help_text='Без дубля бренду, напр. Соус «Сладкий Чили»', max_length=255, verbose_name='Назва')),
                ('name_ru', models.CharField(help_text='Без дубля бренду, напр. Соус «Сладкий Чили»', max_length=255, null=True, verbose_name='Назва')),
                ('name_uz', models.CharField(help_text='Без дубля бренду, напр. Соус «Сладкий Чили»', max_length=255, null=True, verbose_name='Назва')),
                ('name_en', models.CharField(help_text='Без дубля бренду, напр. Соус «Сладкий Чили»', max_length=255, null=True, verbose_name='Назва')),
                ('package', models.CharField(help_text='Напр. 235 гр., 1 л., 4,5 гр.', max_length=64, verbose_name='Фасування')),
                ('package_ru', models.CharField(help_text='Напр. 235 гр., 1 л., 4,5 гр.', max_length=64, null=True, verbose_name='Фасування')),
                ('package_uz', models.CharField(help_text='Напр. 235 гр., 1 л., 4,5 гр.', max_length=64, null=True, verbose_name='Фасування')),
                ('package_en', models.CharField(help_text='Напр. 235 гр., 1 л., 4,5 гр.', max_length=64, null=True, verbose_name='Фасування')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('image', models.ImageField(upload_to='catalog/products/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['brand__order', 'order', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='catalog_pro_categor_891fe8_idx'), models.Index(fields=['brand', 'is_active'], name='catalog_pro_brand_i_ca0f3c_idx')],
            },
        ),
    ]
