# Generated by Django 5.2.16 on 2026-07-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_brand_logo_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='is_featured',
            field=models.BooleanField(default=True, help_text='Показувати в блоці виробників під каталогом на /products', verbose_name='Під каталогом'),
        ),
    ]
