# Generated by Django 5.2.16 on 2026-08-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_brand_name_i18n'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=128, null=True, verbose_name='Название')),
                ('name_uz', models.CharField(max_length=128, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=128, null=True, verbose_name='Название')),
                ('icon', models.ImageField(blank=True, help_text='Пусто — стандартная иконка из static/img/product-filters/.', null=True, upload_to='catalog/filters/', verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Фильтр товара',
                'verbose_name_plural': 'Фильтры товаров',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='extra_filters',
            field=models.ManyToManyField(blank=True, help_text='Иконки свойств на карточке. Назначаются вручную.', related_name='products', to='catalog.productfilter', verbose_name='Дополнительные фильтры'),
        ),
    ]
